fix (workflows): fix github action

diff --git a/.github/workflows/repository_state.yml b/.github/workflows/repository_state.yml
--- a/.github/workflows/repository_state.yml
+++ b/.github/workflows/repository_state.yml
@@ -14,4 +14,4 @@ jobs:
     steps:
       - uses: actions/checkout@v1
       - name: Build
-        run: make re
+        run: make re > /dev/null && echo -e "\e[1m\e[32m\n► BUILD SUCCESS !\e[0m" || echo -e "\e[1m\e[31m\n► BUILD FAILED !\e[0m"
